# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_RISCV_CBQRI)			+= cbqri.o
cbqri-y						+= cbqri_devices.o
cbqri-$(CONFIG_RISCV_CBQRI_RESCTRL_FS)		+= cbqri_resctrl.o
cbqri-$(CONFIG_RISCV_CBQRI_CAPACITY)		+= cbqri_capacity.o
