# SPDX-License-Identifier: GPL-2.0-only
# SYNOPSYS Platform Support
obj-$(CONFIG_CANAAN_SND_DESIGNWARE_I2S) += canaan-designware_i2s.o

canaan-designware_i2s-y := canaan-dwc-i2s.o
canaan-designware_i2s-$(CONFIG_CANAAN_SND_DESIGNWARE_PCM) += canaan-dwc-pcm.o
