# CPU DAI drivers

snd-soc-xuantie-th1520-i2s-objs := th1520-i2s-common.o	\
				       th1520-pcm-dma.o		\
				       th1520-i2s.o
obj-$(CONFIG_SND_SOC_XUANTIE_TH1520_I2S) += snd-soc-xuantie-th1520-i2s.o

snd-soc-xuantie-th1520-i2s-ch8-objs := th1520-i2s-common.o	\
				       th1520-pcm-dma.o		\
				       th1520-i2s-8ch.o
obj-$(CONFIG_SND_SOC_XUANTIE_TH1520_I2S_CH8) += snd-soc-xuantie-th1520-i2s-ch8.o

obj-$(CONFIG_SND_SOC_XUANTIE_TH1520_HDMI_PCM) += th1520-hdmi-pcm.o
